# Lab 6 Tasks

In this notebook we will analyse a dataset from an Irish triathlon by using the Pandas library. In the dataset, each row represents an athlete, described by a number of different descriptive features:

- *Number:* The athlete's race bib number
- *Place:* The place in which the athlete finished the race
- *Age:* The athlete's age
- *Gender:* The gender that the athlete declared ('M' or 'F')
- *Province:* The Irish province where the athlete comes from (Leinster, Munster, Connacht, Ulster)
- *Swim:* The time taken for the swimming segment of the event (in seconds)
- *T1:* The time taken for the first transition of the event, from cycling to swimming (in seconds)
- *Cycle:* The time taken for the cycling segment of the event (in seconds)
- *T2:* The time taken for the swimming segment of the event, from swimming to running (in seconds)
- *Run:* The time taken for the running segment of the event (in seconds)

In [1]:
import pandas as pd

## Task 1 - Data Loading and Preparation

This task required the file 'triathlon.csv'. Load the dataset into a Pandas DataFrame, where the row index is given by the athlete's bib number. Display the first 20 rows of the DataFrame.

In [2]:
df = pd.read_csv("triathlon.csv")
df.head(20)
df.shape

(188, 10)

The dataset might contain missing values. For instance, some athletes may have registered for the race for never actually. Other athletes might have started the race, but not completed all segments of the triathlon.

From the DataFrame, identify the number of missing values in each column. Then remove any rows which contain missing values (i.e. athletes who did not fullly complete the race). How many rows are remaining?

In [3]:
df.isnull().sum()

Number      0
Place       4
Gender      0
Age         0
Province    0
Swim        0
T1          1
Cycle       1
T2          2
Run         6
dtype: int64

In [4]:
# df.loc[df["Place"].isnull()]
df1 = df.dropna()

Add a new column to the DataFrame, called *Finish*, which is the total time taken for the race for each athlete (i.e. Swim + T1 + Cycle + T2 + Run).

In [5]:
df1["Finish"] = df1["Swim"] + df1["T1"] + df1["Cycle"] + df1["T2"] + df1["Run"]

C:\Users\jackt\AppData\Local\Temp\ipykernel_27268\2949201907.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Finish"] = df1["Swim"] + df1["T1"] + df1["Cycle"] + df1["T2"] + df1["Run"]

To verify the step above, sort the DataFrame, based on the *Finish* time, fastest to slowest. Display the top 10 fastest athletes overall:

In [6]:
df1.sort_values("Finish", ascending=True).head(10)

,Number,Place,Gender,Age,Province,Swim,T1,Cycle,T2,Run,Finish
182,183,1.0,M,36,Ulster,577,73.0,1867.0,47.0,1195.0,3759.0
47,48,2.0,M,32,Munster,616,87.0,2016.0,58.0,1225.0,4002.0
53,54,3.0,M,35,Ulster,621,85.0,1982.0,53.0,1282.0,4023.0
91,92,4.0,M,49,Leinster,621,89.0,2005.0,53.0,1474.0,4242.0
117,118,5.0,M,52,Munster,621,104.0,2169.0,51.0,1322.0,4267.0
62,63,6.0,M,34,Munster,688,107.0,2197.0,60.0,1224.0,4276.0
109,110,7.0,M,41,Leinster,601,89.0,2188.0,49.0,1374.0,4301.0
87,88,8.0,M,48,Munster,877,81.0,2114.0,59.0,1192.0,4323.0
88,89,9.0,M,45,Munster,700,103.0,2230.0,45.0,1248.0,4326.0
152,153,10.0,F,35,Munster,666,80.0,2342.0,54.0,1207.0,4349.0

## Task 2 - Initial Data Analysis

What is the average finishing time for athletes? What is the slowest finishing time?

In [7]:
df1["Finish"].max()

7888.0

In [8]:
df1["Finish"].mean()

5359.840659340659

On average which segment of the race took the longest: swimming, cycling or running?

In [9]:
print(f"Swimming average: {df1["Swim"].mean()}")
print(f"Cycling average: {df1["Cycle"].mean()}")
print(f"Running average: {df1["Run"].mean()}")

Swimming average: 854.6373626373627
Cycling average: 2623.285714285714
Running average: 1621.5494505494505

How many female and male athletes competed in the race? How many athletes from each Irish province competed in the race?

In [10]:
df1["Gender"].value_counts()

Gender
M    134
F     48
Name: count, dtype: int64

In [11]:
df1["Province"].value_counts()

Province
Leinster    75
Munster     55
Ulster      30
Connacht    22
Name: count, dtype: int64

How many female and male athletes were from each of the 4 provinces? 

(Hint: We can use a cross-tabulation)

In [12]:
pd.crosstab(df1["Province"], df1["Gender"])

Gender     F   M
Province
Connacht   6  16
Leinster  20  55
Munster   16  39
Ulster     6  24

## Task 3 - Further Data Analysis

Create a new column 'AgeCategory' that divides the runners into age categories: 16-19, 20-29, 30-39, 40-49, 50-65.

In [13]:
bins = [16, 20, 30, 40, 50, 65]
# here we specify right=False to exclude the rightmost edge
df1["AgeCategory"] = pd.cut(df1["Age"], bins=bins, right=False)
df1.head()

C:\Users\jackt\AppData\Local\Temp\ipykernel_27268\4234086105.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["AgeCategory"] = pd.cut(df1["Age"], bins=bins, right=False)

,Number,Place,Gender,Age,Province,Swim,T1,Cycle,T2,Run,Finish,AgeCategory
0,1,11.0,M,19,Munster,518,64.0,2293.0,42.0,1446.0,4363.0,"[16, 20)"
1,2,129.0,M,25,Leinster,1102,124.0,2662.0,47.0,1723.0,5658.0,"[20, 30)"
2,3,35.0,M,25,Leinster,693,138.0,2472.0,42.0,1466.0,4811.0,"[20, 30)"
3,4,153.0,M,26,Munster,906,318.0,3002.0,62.0,1648.0,5936.0,"[20, 30)"
4,5,34.0,M,21,Connacht,566,131.0,2518.0,65.0,1522.0,4802.0,"[20, 30)"

How many female and male athletes were from each age category? 

(Hint: We can use a cross-tabulation and the 'AgeCategory' column created above)

In [17]:
# pd.crosstab(df1["Gender"], df1["AgeCategory"])
pd.crosstab(df1["AgeCategory"], df1["Gender"])

Gender        F   M
AgeCategory
[16, 20)      0   1
[20, 30)     12  20
[30, 40)     19  56
[40, 50)     13  41
[50, 65)      4  16

What was finishing place for each athlete per province?

(Hint: We can perform group-by aggregation)

In [24]:
group1 = df1.groupby(df1["Province"])
group1.min().sort_values("Finish", ascending=True)

,Number,Place,Gender,Age,Swim,T1,Cycle,T2,Run,Finish,AgeCategory
Province,,,,,,,,,,,
Ulster,9,1.0,F,21,577,73.0,1867.0,27.0,1195.0,3759.0,"[20, 30)"
Munster,1,2.0,F,19,518,64.0,2016.0,41.0,1192.0,4002.0,"[16, 20)"
Leinster,2,4.0,F,20,565,89.0,2005.0,42.0,978.0,4242.0,"[20, 30)"
Connacht,5,27.0,F,21,566,108.0,2284.0,61.0,1315.0,4688.0,"[20, 30)"

What were the average times for the three segments, per age category?

(Hint: We can perform group-by aggregation)

In [31]:
group2 = df1.groupby(df1["AgeCategory"])
group2[["Run", "Cycle", "Swim"]].mean()

C:\Users\jackt\AppData\Local\Temp\ipykernel_27268\1775796298.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  group2 = df1.groupby(df1["AgeCategory"])

                     Run        Cycle    Swim
AgeCategory
[16, 20)     1446.000000  2293.000000  518.00
[20, 30)     1624.625000  2802.031250  839.75
[30, 40)     1552.840000  2566.346667  836.76
[40, 50)     1660.277778  2576.611111  888.50
[50, 65)     1778.500000  2693.350000  870.90