# Lab 9 Tasks

In this we will look at using superised machine learning algorithms to predict music genres. Specficially, the objective here is to classify the genre of a song from Spotify, based on a range of associated audio features.

Each song in our dataset is described by a range of features:
- artist_name: Song artist 
- track_name: Song track name
- acousticness: Describes the likelihood that the song is purely acoustic
- danceability: Describes how suitable a track is for dancing based on a combination of elements including tempo, rhythm stability, beat strength, and overall regularity
- energy: A perceptual measure of intensity and activity. More energetic tracks feel fast, loud, and noisy
- instrumentalness: Indicates whether a song includes vocals or not
- liveness: Describes the likelihood that the song was recorded with a live audience.
- loudness: Overall loudness of a track in decibels (dB), averaged across the entire track
- speechiness:  Describes the likelihood that the song contains spoken words
- tempo: Estimated tempo of a track in beats per minute (BPM)
- valence: Tracks with high valence sound more positive (e.g. cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, angry)
- genre: Target label ('Pop' or 'Rock' in this case)

Original dataset source: 
https://www.kaggle.com/code/iqbalbasyar/spotify-genre-classification/data

Original Spotify documentation:
https://developer.spotify.com/discover/

## Task 1

Load the dataset from the file 'music.csv' and examine the number of songs having each target label.

In [17]:
import pandas as pd
from sklearn.model_selection import cross_val_score
# imports for plotting
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

df = pd.read_csv("music.csv")

df.head()
# df["genre"].value_counts()

,artist_name,track_name,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,genre
0,Led Zeppelin,Black Dog,27.40000,43.2,84.8,3.44000,23.30,-8.095,8.78,81.201,74.3,Rock
1,Mike Posner,Song About You,18.00000,67.6,84.9,0.00237,9.98,-3.008,4.12,87.025,64.1,Pop
2,Van Morrison,Days Like This,65.80000,66.0,54.1,0.12700,9.28,-7.851,5.76,93.744,69.3,Rock
3,The 1975,Give Yourself A Try,0.00306,31.3,80.0,0.00000,49.70,-5.011,6.83,183.047,87.1,Rock
4,HUNNY,Parking Lot,0.30300,49.8,84.4,0.00000,35.50,-5.163,4.74,103.970,46.9,Rock

Remove any non-numeric features from the dataset, and then separate out the features to use for classification from the target label information.

In [18]:
# df.isna()
df.drop(["artist_name", "track_name"], axis=1, inplace=True)
df.head()

,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,genre
0,27.40000,43.2,84.8,3.44000,23.30,-8.095,8.78,81.201,74.3,Rock
1,18.00000,67.6,84.9,0.00237,9.98,-3.008,4.12,87.025,64.1,Pop
2,65.80000,66.0,54.1,0.12700,9.28,-7.851,5.76,93.744,69.3,Rock
3,0.00306,31.3,80.0,0.00000,49.70,-5.011,6.83,183.047,87.1,Rock
4,0.30300,49.8,84.4,0.00000,35.50,-5.163,4.74,103.970,46.9,Rock

In [ ]:
target = df["genre"]
data = df.drop("genre", axis=1).copy()
data.head()

,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,genre
0,27.40000,43.2,84.8,3.44000,23.30,-8.095,8.78,81.201,74.3,Rock
1,18.00000,67.6,84.9,0.00237,9.98,-3.008,4.12,87.025,64.1,Pop
2,65.80000,66.0,54.1,0.12700,9.28,-7.851,5.76,93.744,69.3,Rock
3,0.00306,31.3,80.0,0.00000,49.70,-5.011,6.83,183.047,87.1,Rock
4,0.30300,49.8,84.4,0.00000,35.50,-5.163,4.74,103.970,46.9,Rock

## Task 2

Generate a 60/40 random training and test split of the data. Based on this split, evaluate the accuracy and F1-score achieved by a KNN classifier (for *k=1* neighbour).

In [ ]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(data, target, test_size=0.4, random_state=1)
print(f"Training size is {data_train.shape[0]}")
print(f"Test size is {data_test.shape[0]}")

Training size is 1500
Test size is 1000

In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
m = knn.fit(data_train, target_train)
predicted = knn.predict(data_test)

In [39]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(target_test, predicted)
print(f"Accuracy = {acc}")

from sklearn.metrics import f1_score
print(f"f1 score (rock) = {f1_score(target_test, predicted, pos_label="Rock"): .3f}")
print(f"f1 score (pop) = {f1_score(target_test, predicted, pos_label="Pop"): .3f}")

Accuracy = 0.615
f1 score (rock) =  0.618
f1 score (pop) =  0.612

Use a *confusion matrix* to illustrate where the errors lie with the classifier above.

In [ ]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

## Task 3

Use 5-fold cross-validation to evaluate the accuracy achieved by a KNN (*k=1*) classifier on the data.

Repeat the process above for different parameter values of *k*, from 2 to 10 neighbours. Generate a plot of the different accuracy values acheived for different values of *k*. Which value of *k* yields the highest accuracy?

## Task 4

For certain datasets, classification may work better on a subset of features, rather than on the entire feature set (e.g. when noisy or misleading features are removed).

Using the KNN and the best value of *k* identified in Task 3, compare classification performance for the three feature subsets in the lists below. Which subset gives the highest accuracy?

In [ ]:
subset1 = ['danceability', 'energy', 'tempo', 'valence']
subset2 = ['acousticness', 'instrumentalness', 'liveness', 'speechiness']
subset3 = ['energy', 'tempo', 'valence', 'loudness']